CREATE EXTENSION postgis;

SELECT * FROM pg_available_extensions WHERE name = 'postgis';


CREATE TABLE track (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       vehicle_id int REFERENCES vehicle(vehicle_id) ON DELETE SET NULL,
                       location GEOMETRY(Point, 4326)
);

INSERT INTO track (gps_of_vehicle_id, location) VALUES (1, ST_GeomFromText('POINT(40.7128 -74.0060)', 4326));
INSERT INTO track (gps_of_vehicle_id, location) VALUES (1, ST_GeomFromText('POINT(34.0522 -118.2437)', 4326));
INSERT INTO track (gps_of_vehicle_id, location) VALUES (1, ST_GeomFromText('POINT(51.5074 -0.1278)', 4326));