SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE gps_points;
TRUNCATE TABLE trips;
TRUNCATE TABLE vehicles_drivers;
TRUNCATE TABLE driver;
TRUNCATE TABLE vehicle;
TRUNCATE TABLE enterprise_manager;
TRUNCATE TABLE simple_user;
TRUNCATE TABLE manager;
TRUNCATE TABLE brand;
TRUNCATE TABLE enterprise;

SET REFERENTIAL_INTEGRITY TRUE;
