{
 "title": "Autopark - Overview",
 "tags": [ "autopark" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Autopark uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"autopark-app\"})"
    }
   ]
  },
  {
   "title": "HTTP requests rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"autopark-app\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP p95 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_requests_seconds_bucket{job=\"autopark-app\"}[5m])) by (le)\r\n)"
    }
   ]
  }
 ]
}