CREATE TABLE Brand (
                       brand_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       brand_name varchar(50) NOT NULL,
                       type int NOT NULL,
                       capacity_fuel_tank int NOT NULL,
                       load_capacity int NOT NULL,
                       number_of_seats int NOT NULL
);

CREATE TABLE Enterprise (
                            enterprise_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            enterprise_name varchar(50) NOT NULL,
                            city_of_enterprise varchar(50) NOT NULL
);

CREATE TABLE Vehicle (
                         vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         vehicle_name varchar(50) NOT NULL,
                         vehicle_cost int NOT NULL,
                         vehicle_year_of_release int NOT NULL,
                         brand_owner int REFERENCES brand(brand_id) ON DELETE SET NULL,
                         enterprise_owner_of_vehicle int REFERENCES enterprise(enterprise_id) ON DELETE SET NULL
);

CREATE TABLE Driver (
                        driver_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        driver_name varchar(50) NOT NULL,
                        driver_salary double precision NOT NULL,
                        enterprise_owner_of_driver int REFERENCES enterprise(enterprise_id) ON DELETE SET NULL,
                        is_active boolean DEFAULT FALSE,
                        active_vehicle int UNIQUE REFERENCES vehicle(vehicle_id) ON DELETE CASCADE
);

CREATE TABLE driver_vehicle (
                                driver_id int REFERENCES driver(driver_id) ON DELETE SET NULL,
                                vehicle_id int REFERENCES vehicle(vehicle_id) ON DELETE SET NULL,
                                PRIMARY KEY(driver_id, vehicle_id)
);

INSERT INTO Brand (brand_name, type, capacity_fuel_tank, load_capacity, number_of_seats) VALUES ('Lada', 2, 50, 400, 4);
INSERT INTO Brand (brand_name, type, capacity_fuel_tank, load_capacity, number_of_seats)  VALUES ('Toyota', 2, 65, 480, 4);
INSERT INTO Brand (brand_name, type, capacity_fuel_tank, load_capacity, number_of_seats)  VALUES ('BMW', 2, 80, 600, 4);

INSERT INTO Enterprise (enterprise_name, city_of_enterprise) VALUES ('Автоваз','Москва');
INSERT INTO Enterprise (enterprise_name, city_of_enterprise) VALUES ('BMW AG','Мюнхен');
INSERT INTO Enterprise (enterprise_name, city_of_enterprise) VALUES ('Toyota Motor Corporation','Тоёта');

INSERT INTO Vehicle(vehicle_name, vehicle_cost, vehicle_year_of_release, brand_owner, enterprise_owner_of_vehicle) VALUES
    ('Kalina 2', 1000000, 2013, 1, 1);
INSERT INTO Vehicle(vehicle_name, vehicle_cost, vehicle_year_of_release, brand_owner, enterprise_owner_of_vehicle) VALUES
    ('Granta', 900000, 2011, 1, 1);
INSERT INTO Vehicle(vehicle_name, vehicle_cost, vehicle_year_of_release, brand_owner, enterprise_owner_of_vehicle) VALUES
    ('XRAY', 1500000, 2011, 1, 1);
INSERT INTO Vehicle(vehicle_name, vehicle_cost, vehicle_year_of_release, brand_owner, enterprise_owner_of_vehicle) VALUES
    ('X 7', 9999999, 2017, 3, 2);
INSERT INTO Vehicle(vehicle_name, vehicle_cost, vehicle_year_of_release, brand_owner, enterprise_owner_of_vehicle) VALUES
    ('Camry', 850000, 2014, 2, 3);
INSERT INTO Vehicle(vehicle_name, vehicle_cost, vehicle_year_of_release, brand_owner, enterprise_owner_of_vehicle) VALUES
    ('RAV4', 2000000, 2016, 2, 3);

INSERT INTO Driver (driver_name, driver_salary, enterprise_owner_of_driver, active_vehicle) VALUES ('Попов В.К.', 70000);
INSERT INTO Driver (driver_name, driver_salary, enterprise_owner_of_driver, active_vehicle) VALUES ('Туркин Л.М.', 80000);
INSERT INTO Driver (driver_name, driver_salary, enterprise_owner_of_driver, active_vehicle) VALUES ('Логинов И.К.', 85000);
INSERT INTO Driver (driver_name, driver_salary, enterprise_owner_of_driver, active_vehicle) VALUES ('Майоров Н.Т.', 60000);
INSERT INTO Driver (driver_name, driver_salary, enterprise_owner_of_driver, active_vehicle) VALUES ('Ломов В.В.', 90000);
INSERT INTO Driver (driver_name, driver_salary, enterprise_owner_of_driver, active_vehicle) VALUES ('Зайкин К.Р.', 100000);